name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Jest
      run: |
          npm install locutus --save
      uses: actions/checkout@v2
      run: |
          make test